### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by aaronreichmenberliner** [aymeric-spiga/mcd-python#30]
I am currently trying to install your mcd-python interface, but I am having trouble with the F2PY features. I have successfully
 
* Compiled NETCDF with the `-fPIC` options as described in your `netcdf/gfortran_netcdf4_fPIC` file (I have tried downloading the NETCDF C and Fortran libraries, but compiling MCD seems to work better when the C libraries are used).
* Compiled MCD (version 5.2) with the fPIC NETCDF library
* Updated my `bashrc` profile via the appropriate `PYTHONPATH`
* Verified that `compile_fmcd.sh` links to the NETCDF libs and MCD directories.
* Checked that `f2py` is installed. I have run with both `PY2.7` and `PY3.6`, but I always get an error here.
 
During the command `f2py -h fmcd$num.pyf -m fmcd$num tmp.call_mcd.F tmp.julian.F tmp.heights.F > fmcd$num.log 2>&1` (for me line 57 of `compile_fmcd.sh`) I get an error:
 
```
analyzeline: Failed to evaluate '.true.'. Ignoring: invalid syntax (<string>, line 1)
Reading fortran codes...
                Reading file 'tmp.call_mcd.F' (format:fix,strict)
                Reading file 'constants_mcd.inc' (format:fix)
Line #14 in constants_mcd.inc:"      parameter (output_messages=.true.)"
                determineexprtype: could not determine expressions ('.true.') type.
Traceback (most recent call last):
  File "/Users/aaronberliner/anaconda3/bin/f2py", line 28, in <module>
    main()
  File "/Users/aaronberliner/anaconda3/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 650, in main
    run_main(sys.argv[1:])
  File "/Users/aaronberliner/anaconda3/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 408, in run_main
    postlist = callcrackfortran(files, options)
  File "/Users/aaronberliner/anaconda3/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/Users/aaronberliner/anaconda3/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 3246, in crackfortran
    readfortrancode(files, crackline)
  File "/Users/aaronberliner/anaconda3/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 495, in readfortrancode
    readfortrancode(fn, dowithline=dowithline, istop=0)
  File "/Users/aaronberliner/anaconda3/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 421, in readfortrancode
    'this code is in fix form?\n\tline=%s' % repr(l))
Exception: readfortrancode: Found non-(space,digit) char in the first column.
                Are you sure that this code is in fix form?
                line='n '
 ```

The error in this line seems to prevent downstream operations and the log will eventually read
```
Traceback (most recent call last):
  File "/Users/aaronberliner/anaconda3/bin/f2py", line 28, in <module>
    main()
  File "/Users/aaronberliner/anaconda3/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 648, in main
    run_compile()
  File "/Users/aaronberliner/anaconda3/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 622, in run_compile
    ext = Extension(**ext_args)
  File "/Users/aaronberliner/anaconda3/lib/python3.6/site-packages/numpy/distutils/extension.py", line 54, in __init__
    export_symbols=export_symbols)
  File "/Users/aaronberliner/anaconda3/lib/python3.6/distutils/extension.py", line 104, in __init__
    raise AssertionError("'name' must be a string")
AssertionError: 'name' must be a string
```
As there doesn't seem to be a `fmcd.pyf` file created.

**Comment by aymeric-spiga** [comment]
Thanks @aaronreichmenberliner for your feedback! It normally works fine with ```f2py``` (python 2.7 version) using the gfortran compiler. ```mcd-python``` is used in the online web interface ```mcd_python``` using the ```compile_fmcd.sh``` script

Maybe the netCDF file you compiled is not the right one. I corrected the netCDF compile script (see commit https://github.com/aymeric-spiga/mcd-python/commit/96c924ef0fd00a4b1edd39889566b7a218cf3490) so that it downloads the version that works for me.

Another problem could be that ```f2py``` is not using ```gfortran``` as a compiler. You can have a look to this by using the command
```
f2py -c --help-fcompiler
```

**Comment by aaronreichmenberliner** [comment]
Hi! 

Wow! Fast reply! First, I blew away my `mcd-python` and rebuilt my NETCDF using your new script. It worked like a charm and I tested it by recompiling the full `mcd` using the new NETCDF directory. Beautiful. 

Running the `f2py -c --help-fcompiler` gives

```
Gnu95FCompiler instance properties:
  archiver        = ['/usr/local/bin/gfortran', '-cr']
  compile_switch  = '-c'
  compiler_f77    = ['/usr/local/bin/gfortran', '-Wall', '-g', '-ffixed-
                    form', '-fno-second-underscore', '-arch', 'x86_64', '-
                    fPIC', '-O3', '-funroll-loops']
  compiler_f90    = ['/usr/local/bin/gfortran', '-Wall', '-g', '-fno-second-
                    underscore', '-arch', 'x86_64', '-fPIC', '-O3', '-funroll-
                    loops']
  compiler_fix    = ['/usr/local/bin/gfortran', '-Wall', '-g', '-ffixed-
                    form', '-fno-second-underscore', '-Wall', '-g', '-fno-
                    second-underscore', '-arch', 'x86_64', '-fPIC', '-O3', '-
                    funroll-loops']
  libraries       = ['gfortran']
  library_dirs    = ['/usr/local/gfortran/lib/gcc/x86_64-apple-
                    darwin16/6.3.0', '/usr/local/gfortran/lib/gcc/x86_64-apple
                    -darwin16/6.3.0/../../..',
                    '/usr/local/gfortran/lib/gcc/x86_64-apple-
                    darwin16/6.3.0/../../..']
  linker_exe      = ['/usr/local/bin/gfortran', '-Wall', '-Wall']
  linker_so       = ['/usr/local/bin/gfortran', '-Wall', '-g', '-arch',
                    'x86_64', '-Wall', '-g', '-undefined', 'dynamic_lookup', '
                    -bundle']
  object_switch   = '-o '
  ranlib          = ['/usr/local/bin/gfortran']
  version         = LooseVersion ('6.3.0')
  version_cmd     = ['/usr/local/bin/gfortran', '-dumpversion']
GnuFCompiler instance properties:
  archiver        = ['/usr/local/bin/g77', '-cr']
  compile_switch  = '-c'
  compiler_f77    = ['/usr/local/bin/g77', '-g', '-Wall', '-fno-second-
                    underscore', '-fPIC', '-O3', '-funroll-loops']
  compiler_f90    = None
  compiler_fix    = None
  libraries       = ['g2c', 'cc_dynamic']
  library_dirs    = ['/usr/local/lib/gcc/i686-apple-darwin8.8.1/3.4.0',
                    '/usr/local/lib/gcc/i686-apple-
                    darwin8.8.1/3.4.0/../../..']
  linker_exe      = ['/usr/local/bin/g77', '-g', '-Wall', '-g', '-Wall']
  linker_so       = ['/usr/local/bin/g77', '-g', '-Wall', '-g', '-Wall', '-
                    undefined', 'dynamic_lookup', '-bundle']
  object_switch   = '-o '
  ranlib          = ['/usr/local/bin/g77']
  version         = LooseVersion ('3.4.0')
  version_cmd     = ['/usr/local/bin/g77', '-dumpversion']
Fortran compilers found:
  --fcompiler=gnu    GNU Fortran 77 compiler (3.4.0)
  --fcompiler=gnu95  GNU Fortran 95 compiler (6.3.0)
Compilers available for this platform, but not found:
  --fcompiler=absoft  Absoft Corp Fortran Compiler
  --fcompiler=g95     G95 Fortran Compiler
  --fcompiler=ibm     IBM XL Fortran Compiler
  --fcompiler=intel   Intel Fortran Compiler for 32-bit apps
  --fcompiler=nag     NAGWare Fortran 95 Compiler
  --fcompiler=pg      Portland Group Fortran Compiler
Compilers not available on this platform:
  --fcompiler=compaq    Compaq Fortran Compiler
  --fcompiler=flang     Portland Group Fortran LLVM Compiler
  --fcompiler=hpux      HP Fortran 90 Compiler
  --fcompiler=intele    Intel Fortran Compiler for Itanium apps
  --fcompiler=intelem   Intel Fortran Compiler for 64-bit apps
  --fcompiler=intelev   Intel Visual Fortran Compiler for Itanium apps
  --fcompiler=intelv    Intel Visual Fortran Compiler for 32-bit apps
  --fcompiler=intelvem  Intel Visual Fortran Compiler for 64-bit apps
  --fcompiler=lahey     Lahey/Fujitsu Fortran 95 Compiler
  --fcompiler=mips      MIPSpro Fortran Compiler
  --fcompiler=nagfor    NAG Fortran Compiler
  --fcompiler=none      Fake Fortran compiler
  --fcompiler=pathf95   PathScale Fortran Compiler
  --fcompiler=sun       Sun or Forte Fortran 95 Compiler
  --fcompiler=vast      Pacific-Sierra Research Fortran 90 Compiler
For compiler details, run 'config_fc --verbose' setup command.
Removing build directory /var/folders/bk/rkk6___535nfsplpbc3z00r40000gn/T/tmpo5ksboya
```

Then I tried re-testing the `mcd-python` configure script but got the same error at `f2py -h fmcd$num.pyf -m fmcd$num tmp.call_mcd.F tmp.julian.F tmp.heights.F > fmcd$num.log 2>&1` 

That being said, I think the problem is in the `F2PY` part. I noticed that the substitution command `sed` creates some odd stuff (or at least, I am too dense to get it).

I have attached two files (`constants_mcd_mcd.inc`) and (`constants_mcd_mcd_python.inc`) which are the constants files before and after the sed operations on line 52 of `compile_fmcd.sh`. The problem seems to be in the way `!` is turned to `n!`.
[constants_mcd_mcd.inc.txt](https://github.com/aymeric-spiga/mcd-python/files/2020756/constants_mcd_mcd.inc.txt)
[constants_mcd_mcd_python.inc.txt](https://github.com/aymeric-spiga/mcd-python/files/2020757/constants_mcd_mcd_python.inc.txt)

**Comment by aaronreichmenberliner** [comment]
Also, for reference:

**For PY2.7**
`which f2py` gives
`/Users/aaronberliner/anaconda3/envs/PY2_7/bin/f2py`

and `f2py` gives
```
Version:     2
numpy Version: 1.14.2
Requires:    Python 2.3 or higher.
License:     NumPy license (see LICENSE.txt in the NumPy source code)
Copyright 1999 - 2011 Pearu Peterson all rights reserved.
http://cens.ioc.ee/projects/f2py2e/
```

**Comment by aymeric-spiga** [comment]
You're welcome. I happened to be just in front of my computer, and willing to test this! So you are using ```gfortran``` hence everything is fine (I am guessing your ```f2py``` is choosing ```--fcompiler=gnu95``` like mine).

Looks like you have found where the problem is: there is indeed a problem with how the sed file handles the change. Works like a charm on my side, but not on yours. 

Looking at your ```f2py``` settings, looks like you are working with Mac OS, hence BSD-based ```sed```, while I am working with Linux GNU-based ```sed```. It seems BSD-based ```sed``` is interpreting differently newlines in sed [see this stackoverflow page](https://stackoverflow.com/questions/1421478/how-do-i-use-a-new-line-replacement-in-a-bsd-sed) [and also this blog post](http://nlfiedler.github.io/2010/12/05/newlines-in-sed-on-mac.html)

**Comment by aymeric-spiga** [comment]
I tried a fix with commit https://github.com/aymeric-spiga/mcd-python/commit/babf4e365a84cc57940b570df8829025f0589345 please do let me know if that works for you?

**Comment by aaronreichmenberliner** [comment]
Wow again. Yes, that `sed` update fixed it!

I was able to compute the appropriate `.so` file. After moving the `test_mcd.py` and `test_mcd.def` files to the main directory, I was able to make those work as well. **(NOTE: in your current `test_mcd.def` file, you have a value of `8` for the specific scenario, but the standard scenario in the MCD is `1`.)**

I then tried running through the Jupyter Notebook, but I ran into some new trouble in the `req.update` command. :(

<img width="1524" alt="screen shot 2018-05-20 at 5 59 56 pm" src="https://user-images.githubusercontent.com/13181795/40285994-a1d8f60a-5c57-11e8-8dcf-34fe10485ea1.png">

**Comment by aaronreichmenberliner** [comment]
@aymeric-spiga 

Hi Again!

Another question. On line `968` of `mcd.py`, a call is made for a file called `surface.nc` in an outside directory. If possible, can you include this NETCDF file so we can properly visualize the 2D topology?

**Comment by aymeric-spiga** [comment]
The issue found with the notebook should be fixed by commit https://github.com/aymeric-spiga/mcd-python/commit/c9ca0c359d2696380f933ac823d3d1db52e4a194
